version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: student_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306"

  webapp:
    build: .
    container_name: student_webapp
    depends_on:
      - mysql
    ports:
      - "8080:8080"
